server {
    listen 80;
    listen [::]:80;
    server_name iccppglobal.com www.iccppglobal.com;

    client_max_body_size 22m;

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/iccpp/iccpp.sock;
    }
}
